### ISSUE TITLE
iPhone

### ISSUE THREAD

**Issue by Matthewlitteken022007** [AustinWise/iPhoneRestrictionCracker#1]

**Comment by AustinWise** [comment]
@Matthewlitteken022007 Currently your issue is blank:
![image](https://user-images.githubusercontent.com/7751/133915199-f187dcb2-2f54-4c05-92c2-443cc0294b33.png)
Please reopen with more detail if you are having a problem with this software. Please note though that I have not used it 4 years myself, so I don't know if it still works.
